### ISSUE TITLE
Crashes when running with CRA

### ISSUE THREAD

**Issue by lucasbento** [hamlim/inline-mdx.macro#10]
**⚠️ [The reproduction project source can be seen here](https://github.com/lucasbento/inline-mdx-error) ⚠️**

Basically if you run with a fresh `create-react-app` output you get this:

![image](https://user-images.githubusercontent.com/6207220/58483684-02c84180-8161-11e9-9481-1411947356bf.png)

The command I ran is `npx create-react-app my-site && cd my-site && yarn add inline-mdx.macro @mdx-js/tag`

And my `App.js`:

```jsx
import React from 'react';
import './App.css';
import { inline } from "inline-mdx.macro";
import { MDXTag } from "@mdx-js/tag";

const SomeMDXComponent = inline`

## This is some MDX source

~~strikethrough~~
`;

function App() {
  return (
    <SomeMDXComponent/>
  );
}

export default App;
```

**Comment by lucasbento** [comment]
This may be related to #5

**Comment by hamlim** [comment]
Thanks for opening this! 

I took some time to heavily refactor this babel macro to update it to the newest version of MDX, using `@mdx-js/react` instead of `@mdx-js/tag` and a few other improvements. 

I tested this out on your reproduction of the bug (thanks for sharing that), and published an alpha at `inline-mdx.macro@1.0.0-alpha.2` if you would like to test it locally.

Note: With this new version you will need to add `@mdx-js/react` as a dependency, and add the `/** @jsx mdx */` pragma to the top of any file using the `inline` macro.

See the PR here where all these changes are made: https://github.com/hamlim/inline-mdx.macro/pull/11.

I can open a PR on your repo as well with the updates I made 👍🏼

**Comment by hamlim** [comment]
Opened this PR on your reproduction repo: https://github.com/lucasbento/inline-mdx-error/pull/1

**Comment by lucasbento** [comment]
Thank you so much for the prompt response and I appreciate a lot the PR!

I'm gonna check it all out by tomorrow morning (CET timezone).

Again, thank you so much for working in this library and being so helpful!

**Comment by lucasbento** [comment]
This works really well, thank you for doing it!

I'm working on getting `inline-mdx.macro` into [React Native Upgrade Helper](https://github.com/react-native-community/upgrade-helper), gonna have a PR soon including this awesome library there 🙂

Thank you for your work 😄
